name: bit_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  get_storage: ^2.1.1
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  intl: any
  flutter_svg:
  pinput:
  phone_number: 
  intl_phone_field: 
  permission_handler: ^11.3.1 
  persistent_bottom_nav_bar_v2: 
  share_plus: ^7.2.2
  flutter_staggered_grid_view: ^0.7.0

  dotted_border: ^2.1.0 
  image_picker: ^1.0.7 
  fl_chart: ^0.66.2

  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.4.0
  dotted_line: ^3.2.3
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.3
  dio: ^5.4.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  flutter_google_maps_webservices: ^1.1.1
  image_cropper: ^8.0.2
  flutter_polyline_points: ^2.1.0
  cloudinary: ^1.2.0
  socket_io_client: ^3.0.2
  logger: ^2.6.0
  geocoding: ^3.0.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^3.0.0
  url_launcher: ^6.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_full.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/icons/
    - assets/imgs/
    - assets/json/



  fonts:
    - family: Montserrat # <--- CHANGE THIS FROM Satoshi TO Lufga
      fonts:
        # # Lufga Regular
        # - asset: assets/fonts/LufgaRegular.ttf
        #   weight: 400 # Normal/Regular weight
        # - asset: assets/fonts/LufgaItalic.ttf # Assuming this is the italic variant of Lufga Regular
        #   weight: 400 # Should match the regular weight it's an italic variant of
        #   style: italic

        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
   